package com.ironhack.Homework3.enums;

public enum Command {
    //Define the possible commands
    NEW_LEAD, NEW_SALESREP, SHOW_LEADS, SHOW_CONTACTS, SHOW_OPPORTUNITIES, SHOW_ACCOUNTS, SHOW_SALESREPS, LOOKUP_LEAD,
    LOOKUP_ACCOUNT, LOOKUP_OPPORTUNITY, LOOKUP_CONTACT, CONVERT, CLOSE_LOST, CLOSE_WON, HELP, QUIT, CONTINUE,
    REPORT_LEAD_BY_SALESREP, REPORT_OPPORTUNITY_BY_SALESREP, REPORT_CLOSED_WON_BY_SALESREP,
    REPORT_CLOSED_LOST_BY_SALESREP, REPORT_OPEN_BY_SALESREP, REPORT_OPPORTUNITY_BY_THE_PRODUCT,
    REPORT_CLOSED_WON_BY_THE_PRODUCT, REPORT_CLOSED_LOST_BY_THE_PRODUCT, REPORT_OPEN_BY_THE_PRODUCT,
    REPORT_OPPORTUNITY_BY_COUNTRY, REPORT_CLOSED_WON_BY_COUNTRY, REPORT_CLOSED_LOST_BY_COUNTRY,
    REPORT_OPEN_BY_COUNTRY, REPORT_OPPORTUNITY_BY_CITY, REPORT_CLOSED_WON_BY_CITY, REPORT_CLOSED_LOST_BY_CITY,
    REPORT_OPEN_BY_CITY, REPORT_OPPORTUNITY_BY_INDUSTRY, REPORT_CLOSED_WON_BY_INDUSTRY, REPORT_CLOSED_LOST_BY_INDUSTRY,
    REPORT_OPEN_BY_INDUSTRY, MEAN_EMPLOYEECOUNT, MEDIAN_EMPLOYEECOUNT, MAX_EMPLOYEECOUNT, MIN_EMPLOYEECOUNT,
    MEAN_QUANTITY, MEDIAN_QUANTITY, MAX_QUANTITY, MIN_QUANTITY, MEAN_OPPS_PER_ACCOUNT, MEDIAN_OPPS_PER_ACCOUNT,
    MAX_OPPS_PER_ACCOUNT, MIN_OPPS_PER_ACCOUNT

}
